version: "2"
services:
  nginx:
    build: ./nginx
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./application:/var/www/html
    networks:
      - sd-net
    environment:
      APP_ENV: ${APP_ENV}
  php:
    build: ./php
    volumes:
      - ./application:/var/www/html
    networks:
      - sd-net
    environment:
      APP_ENV: ${APP_ENV}
  redis:
    image: redis:alpine
    networks:
      - sd-net
  mysql:
    image: mysql:5.7
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my-app
      MYSQL_USER: app-user
      MYSQL_PASSWORD: app-pass
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - sd-net
networks:
  sd-net:
    driver: "bridge"
volumes:
  mysqldata:
    driver: "local"
